site_name: My Full Stack Python
repo_url: https://github.com/rjNemo/fullstack-python
repo_name: rjNemo/fullstack-python
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime
  font:
    text: Roboto
  language: en
  icon:
    logo: material/fountain-pen
    repo: fontawesome/brands/github
  features:
    - navigation.instant
#    - navigation.tabs
    - header.autohide
    - navigation.top
extra:
  alternate:
    # Switch to English
    - name: French
      link: fr/
      lang: fr
    # Switch to German
    - name: Deutsch
      link: de/
      lang: de
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rjnemo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ruidy-nemausat-522b4069/
nav:
  - index.md
  - introduction.md
  - development-environment.md
  - data.md